formatter: "markdown table"

version: ">= 0.18.0"

sections:
  show:
    - requirements
    - providers
    - resources
    - data-sources
    - inputs
    - outputs

output:
  file: "README.md"
  mode: inject

sort:
  enabled: true
  by: name
