###############################################################################
# Zesty Kompass — EKS cluster: eks-prod
#
# Deploys the Kompass Helm chart into the eks-prod cluster.
# Reads kompass_values_yaml from the account dependency.
#
# Each cluster gets its own directory, own state, own Helm provider.
###############################################################################

include "root" {
  path = find_in_parent_folders("datacenter.hcl")
}

dependency "account" {
  config_path = "../account"
}

locals {
  region_vars  = read_terragrunt_config(find_in_parent_folders("region.hcl")).locals
  region       = local.region_vars.region
  cluster_name = "eks-prod"
}

terraform {
  source = "${get_repo_root()}/examples/multi_clusters/terragrunt/modules/kompass"
}

# ---------------------------------------------------------------------------
# Helm + AWS provider pointing at this specific EKS cluster
# The AWS provider is generated by datacenter.hcl
# ---------------------------------------------------------------------------
generate "helm_provider" {
  path      = "helm_provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
data "aws_eks_cluster" "cluster" {
  name = "${local.cluster_name}"
}

provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", "${local.cluster_name}"]
    }
  }
}
EOF
}

inputs = {
  kompass_values_yaml = dependency.account.outputs.kompass_values_yaml
}
