###############################################################################
# Zesty AWS Account — applied ONCE per AWS account
#
# Creates IAM role + policy and registers the account with Zesty.
# Outputs kompass_values_yaml consumed by the kompass-eks-* directories.
###############################################################################

include "datacenter" {
  path = find_in_parent_folders("datacenter.hcl")
}

terraform {
  source = "tfr:///zesty-co/aws-eks-cluster/zesty?version=0.2.0"
}

# ---------------------------------------------------------------------------
# Zesty provider — The AWS provider is generated by datacenter.hcl
# ---------------------------------------------------------------------------
generate "zesty_provider" {
  path      = "zesty_provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
provider "zesty" {
  token = "your-zesty-api-token" # replace with your actual token
}
EOF
}

inputs = {
  create_values_local_file = false
}
